/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_pojd_rpi_sensors_gpio_Dht22Am2302TemperatureAndHumiditySensor */

#ifndef _Included_cz_pojd_rpi_sensors_gpio_Dht22Am2302TemperatureAndHumiditySensor
#define _Included_cz_pojd_rpi_sensors_gpio_Dht22Am2302TemperatureAndHumiditySensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cz_pojd_rpi_sensors_gpio_Dht22Am2302TemperatureAndHumiditySensor
 * Method:    executeNative
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_cz_pojd_rpi_sensors_gpio_Dht22Am2302TemperatureAndHumiditySensor_executeNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
